security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                #csrf_provider: form.csrf_provider
                
                # login success redirecting options (read further below)
                always_use_default_target_path: true
                default_target_path:            /admin/dashboard
                target_path_parameter:          _target_path
                use_referer:                    true
            logout:
                path:   /logout
                target: /
                #success_handler: AppBundle:logout
                invalidate_session: true
            anonymous:    true
            
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false